### ISSUE TITLE
Default value required for --auth-type

### ISSUE THREAD

**Issue by nzquagmire** [10gen/realm-cli#247]
Looks like using version 2.3.3 using default login credentials as per Realm UI instructions gives error "login setup failed: unsupported login type, use one of [cloud, local] instead".  I managed to circumvent this by specifying --auth-type flag however this option isn't even listed in the help files...

**Comment by fadi12** [comment]
I got the same error - thanks for the workaround as I was stumped. must be a very fresh issue.

**Comment by makesitgo** [comment]
The fix has been published in `2.3.4`, apologies for the inconvenience here!
