### ISSUE TITLE
Login is not possible, HTTP 426 Upgrade required

### ISSUE THREAD

**Issue by nils-jansen** [10gen/realm-cli#315]
Using the following versions: 
* Ubuntu 20.04
* node 16.16.0
* npm 8.11.0
* realm-cli 2.6.0

CLI was successfully installed with `npm i mongodb-realm-cli --location=global`.

[As instructed by the MongoDB App Services UI](https://www.mongodb.com/docs/atlas/app-services/manage-apps/create/create-with-cli/#authenticate-a-mongodb-atlas-user), I ran `realm-cli login --api-key <key> --private-api-key <private-key>`.
This yields the following output:
![image](https://user-images.githubusercontent.com/20142304/181269598-18ba1253-a06a-42d6-86d1-ccc8a6f1f916.png)

Expected behaviour: successful login with newly generated credentials.

**Comment by makesitgo** [comment]
This appears to be an issue with the local environment and it sounds like HTTP/2 protocol is not supported on that machine (fwiw, login works fine on my end with all recent versions of the CLI)

**Comment by nils-jansen** [comment]
Even though this error message was displayed, login was possible. All I had to do was exit gracefully, not using Ctrl C.
