### ISSUE TITLE
import command for deploy is giving nonsense error about maximum database trigger

### ISSUE THREAD

**Issue by LukasDeco** [10gen/realm-cli#330]
I’m trying to deploy a Realm App via the CLI and my app is tied to an M2 cluster and only has 5 database triggers in it. And here’s the error I’m getting when I try to deploy via the CLI:
error validating trigger: maximum database trigger count for cluster size=‘M0’ is 5

Can anyone from MongoDB and the App Services team help investigate? I can provide app ID to someone who can check this out?

**Comment by tkaye407** [comment]
Hi, we see you have opened up a HELP ticket which is the best way to resolve these matters. I will close this out as we are looking into it there.
