### ISSUE TITLE
Environments not provided failure in CLI v1.3.0

### ISSUE THREAD

**Issue by tylerzisk** [10gen/realm-cli#73]
When running our GitHub Action workflows, we ran into a cryptic failure using the `mongo-realm-cli` v1.3.0. It is missing an `environments` folder under `dist`. Looking at both this repo and the Mongo Realm CLI docs, theres nothing about these environments being required when running with CLI. We simply fixed this issue by downgrading to 1.2.0. A changelog or documentation update would be nice when these things happen.

![Screen Shot 2021-02-22 at 10 58 00 AM](https://user-images.githubusercontent.com/18252118/108749708-61b91700-74fd-11eb-9c98-0ad73123bc8a.png)

**Comment by UnicodeSnowman** [comment]
@tylerzisk I believe this should be fixed in `1.3.x` patch releases, please reopen if this is still an issue, thanks!
